### ISSUE TITLE
parsea alla värden i spiders

### ISSUE THREAD

**Issue by glindstedt** [mvk-team42/Veracitor#15]
tags, publishers och references defaultas nu till tomma arrayer i pipelinen

**Comment by JonathanMurray** [comment]
Ta även fram publisher i db, och uppdatera listan med infos. Vilken publisher det är bör man veta utifrån var scrapingen startades ifrån.

**Comment by glindstedt** [comment]
- rssSpider behöver kolla efter author-tag i rss:en, hoppa inte in i artikel om den finns
- rssSpider och articleSpider måste alltid lägga till url:en som producer

**Comment by JonathanMurray** [comment]
articleSpider anropar scrapeMeta i nuläget (lägger alltså till url:en som producer). 

scrapeArticle yieldar i nuläget newspapern om den scrapas med meta, men den borde även läggas till i information-item som scrapas.
