### ISSUE TITLE
callback och returvärde i compute_trust

### ISSUE THREAD

**Issue by mrunelov** [mvk-team42/Veracitor#21]
@johntu @antonaut @mold 

Har skrivit en set_callback-funktion i tidaltrust nu. Ser ut såhär:

``` python
callback_function

def set_callback(callback):
    global callback_function
    callback_function = callback
```

och används såhär i slutet på compute_trust:

``` python
if callback_function != None:
    callback_function()

return trust
```

Och har lite frågor (plus att koden möjligvis är fel nånstans/överallt).
1. Ska callback-anropet ha några parametrar? Vad ska isf skickas med? Den kanske helt ska ersätta returvärde (dvs vi skickar med det i callbacken istället)
2. Vill web ha en tupel som returvärde med trust-värde + grafväg som användes? Just nu ges bara trustvärde. Ganska säker på att den vill ha det men glömt om vi la det på is eller inte :p

**Comment by mold** [comment]
Pratade med John igår och vi kom fram till att detta inte är så viktigt. Det kommer bara vara en temporär lösning tills hela Celery-delen är färdig, eftersom man med hjälp av den kan bestämma vart `compute_trust` ska returnera (om jag förstod allt rätt).

**Comment by mold** [comment]
Angående vad som ska returneras vill man väl ha typ så mycket info som möjligt från uträkningen. I en dict kanske. Exakt vad som returneras får vi komma överens om eller dokumentera utförligt i tidaltrust.

**Comment by mrunelov** [comment]
Bra, låter som att returneringen kanske är löst då. Då återstår bara att bestämma exakt vad vi ska returnera och hur
