### ISSUE TITLE
Mer sofistikerat gränssnitt i databasklasserna

### ISSUE THREAD

**Issue by JonathanMurray** [mvk-team42/Veracitor#32]
Producer-klassen i nuläget: En lista med source_rating-objekt. Väldigt svårt att göra saker som att "rata dn 5 på terrorism". Tänk om den redan var ratad 4. Då måste man först kolla det och sedan ta bort, osv.

Vill ha metoder typ:
- rate_source(source, tag, rating)  - har gjort en stub för denna
- get_rating(source, tag)

Skulle vara enklare att implementera dessa om man lät Ratings vara dicts snarare än lists. (Finns DictField i MongoEngine) Dictsen skulle mappa från (Producer, Tag)-par till ratings (ints)

**Comment by mrunelov** [comment]
Låter väldigt bra, och jag tror att det skulle gå relativt smidigt att fixa va?

**Comment by Alfred26** [comment]
Jag fixar det.

**Comment by Alfred26** [comment]
Efter att ha suttit med det ett tag så inser jag att det inte går så smidigt eftersom att globalNetwork (networkModel) har många metoder som bygger på att SourceRatings och InformationRatings finns som egna objekt. Finns det inte några andra som byggt kod utefter hur det sett ut hittills när det gäller ratingssystemet? 

Jag tänker mig att vi kan skriva metoderna utan att ändra på strukturen, genom att metoderna scannar av befintliga ratings och ersätter vid behov.

**Comment by mrunelov** [comment]
Tror inte att vi skrivit rate-metoder alls i web eller algo. Men fråga crawl vad dom gjort senaste dagarna iaf.

**Comment by Alfred26** [comment]
Implementerat dem som potentiellt prestandakrävande loop, ligger uppe på databasebranchen.

**Comment by JonathanMurray** [comment]
Det får duga så länge, tycker jag :)
