### ISSUE TITLE
Tidaltrust

### ISSUE THREAD

**Issue by antonaut** [mvk-team42/Veracitor#4]
@mold 

Finns det ngn speciell anledning till att Tidaltrust ligger i en klass och är statiska metoder istället för bara vanliga funktioner :question: 

Man importerar ju iaf hela modulen, så istället för 

```
from tidaltrust import Tidaltrust
...
Tidaltrust.compute_trust(...)
```

blir det:

```
import tidaltrust

tidaltrust.compute_trust(...)
```

:smile:

**Comment by JonathanMurray** [comment]
Bra poäng! :+1: 
Enda vitsen med en klassbaserad approach är väl att kunna ha flera TidalTrust samtidigt antar jag. (men det kanske går på nåt vis ändå, mha trådar o grejer?) Nu har ju den potentiella fördelen ändå negerats av att alla metoder är static :P

**Comment by mold** [comment]
Bra fråga. Vi gjorde nog inget medvetet val. Vi får utvärdera strukturen senare, speciellt med tanke på parallella processor osv osv.

Just nu antar jag att vi kan fortsätta på samma sätt då det inte är problematiskt?

**Comment by mrunelov** [comment]
Mjo vi lär ju inte ha något arv dock, så klassen behövs inte annat än för att signalera att metoderna hör ihop (funktioner i en modul kan ju faktiskt ha lite utspridda syften :p). Men jag tror på Modul i slutändan!

**Comment by mrunelov** [comment]
Vi har bytt till modul med funktioner nu. Väntar med att resolva tills vi har rett ut det där med parallella körningar osv.
