### ISSUE TITLE
Misstag i koden?

### ISSUE THREAD

**Issue by JonathanMurray** [mvk-team42/Veracitor#40]
**rate_group i user.py:**
Glömt sätta found = True? (found är alltid False nu)

**notify_producer_was_update i networkModel.py:**
Denna är nog rätt buggig. Producern tas bort från nätverket och läggs sen till igen. Vid borttagningen försvinner alla kanter som nuddar den. (dvs även ratings från andra producers till den, eller hur?) När den sedan läggs till igen läggs det till kanter som motsvarar dess ratings, men kanterna som motsvarar andras ratings är borta :P 

Mitt förslag är att implementera på nåt helt annat sätt, eller att kanske spara undan alla kanter som går till producern i en dict, och lägga till dem igen efter anropet till notify_producer_was_added...

**Comment by Alfred26** [comment]
Vi såg den första buggen. Det andra börjar vi på nu. Vi börjar bli frestade att bygga om ratings till dictionaries, även fast det blir stora interna förändringar av det.
