### ISSUE TITLE
Dictify (konvertering av databas-objekt)

### ISSUE THREAD

**Issue by johnbrynte** [mvk-team42/Veracitor#44]
Metoden **db_to_dict()**, som konverterar databas-objekt till dict-objekt bestående av JavaScript-vänliga typer, är påbörjad i **database.extractor** och behöver _färdigställas_ och _testas_.

(ett bättre namn är också välkommet)

**Comment by mold** [comment]
entity_to_dict?

**Comment by johnbrynte** [comment]
Implementerad med namnbyte enligt ovan.

_**OBS!** Inte helt testad!_

**Comment by mold** [comment]
![turtle-toad-spider](https://f.cloud.github.com/assets/1492711/471183/0f4b9e36-b712-11e2-9cdd-0efba66e5a96.jpg)
