### ISSUE TITLE
Bättre parsing av producers när vi scrapar information.

### ISSUE THREAD

**Issue by JonathanMurray** [mvk-team42/Veracitor#47]
om det står "DN lars larsson" delar vi först upp till [DN, lars, larsson]. Sedan kollar vi om någon av de tre finns i db. DN finns förhoppniungsvis och därför säger vi till db att DN skrev artikeln. Sen fortsätter vi med resten. Varken lars eller larsson finns, så vi lägger till en ny som heter som heter "lars larsson", och säger att han också skrev artikeln. 

Hej tjolahoppsan!

**Comment by mrunelov** [comment]
woooooot :dancers:

**Comment by JonathanMurray** [comment]
Done!
