### ISSUE TITLE
database

### ISSUE THREAD

**Issue by JonathanMurray** [mvk-team42/Veracitor#5]
Ser bra ut med det mesta! :D Här är lite tankar och grejer jag lade märke till:
- Ratings-klasserna borde nog heta Rating (singular) Ett objekt motsvarar ju en rating.
- Vi missade tyvärr 3 metoder i Extractor när vi la in i git:
  - get_all_tags(): Retrieves all tag objects in the database.
  - search_producers(String name, String type): Retrieves all producers that have a name matching the given string, and has the given type.
  - search_informations(String name, Tag[] tags, Date start, Date end): Retrieves all information objects that have a name matching the given string, has at least one of the given tags, and whose production date falls in given time interval.
- Där typen ReferenceField används, borde helst den refererade typen anges och inte Document.
- Vi har visst missförstått varandra lite om hur Tag-klassen ska se ut. Så här tänkte jag:
  - Tags är fördefinierade (eller ändras åtminstonde inte efter att de skapats). En tags valid_strings anger vilka stings/ord som "räknas in i" den tagen. Om man definierar en tag med namn "A" och valid_strings ["A", "a", "aaa"] betyder det att om en användare anger "A", "a" eller "aaa" kommer programmet tolka det som att han menade tagen med namn "A". valid_strings har alltså ingenting att göra med att byta namn på tags. Byta namnet på en tag är förmodligen inte ens ngt man kommer att vilja/kunna göra.
  - Vad tycker ni om det? :)

**Comment by JonathanMurray** [comment]
Och inser att det inte framgår någonstans ur ADDn att det var så jag menade med valid_strings så inte konstigt att vi tänkt olika! :P

**Comment by mold** [comment]
Hade också tankar om valid_strings - i ADD:n finns den överhuvudtaget
endast i databasschemat, utan förklaring. Jag tycker en sådan alias-lösning
känns lite onödigt sofistikerad såhär i början, då man egentligen kan låta
det finnas en lista på färdiga taggar (som ju ska definieras i en hierarki
för att underlätta betygssättning av källor inom olika områden) och bara
tillåta dessa namn, samt eventuellt låta den modul som pratar med databasen
vid taggning "hjälpa" användaren med förslag om man så vill.

Den lördagen den 9:e mars 2013 skrev JonathanMurray:

**Comment by Alfred26** [comment]
"Ratings-klasserna borde nog heta Rating (singular) Ett objekt motsvarar ju en rating."
Ja, det låter klokt :p.

"Vi missade tyvärr 3 metoder i Extractor när vi la in i git:
  get_all_tags(): Retrieves all tag objects in the database."
Yes, lägger in den.

"search_producers(String name, String type): Retrieves all producers that have a name matching the given string, and has the given type.
search_informations(String name, Tag[] tags, Date start, Date end): Retrieves all information objects that have a name matching the given string, has at least one of the given tags, and whose production date falls in given time interval."

Lite förvirrad över de här, vi har väl tänkt att namn unikt ska identifiera både producers och informations? Isåfall så räcker väl metoden get_producer(name)?

"Där typen ReferenceField används, borde helst den refererade typen anges och inte Document."

Vi tänkte också det, men sen blev det en massa problem med circular dependecies. Ex. Producer refererar till information och information refererar till producer, vilket inte går att lösa på något snyggt sätt med importeringarna. 

"Vi har visst missförstått varandra lite om hur Tag-klassen ska se ut. Så här tänkte jag:"

Okej, förstår hur du menar. Vi tar bort TagValidStrings då och stoppar in ett fält i Tag istället. Får se om vi verkligen behöver den som Daniel menar. Om man i GUIn väljer tags från en lista så ser vi inte riktigt poängen med att spara synonymer.

**Comment by Alfred26** [comment]
Allting ligger inne nu.
