### ISSUE TITLE
Database dot (".") storage bug

### ISSUE THREAD

**Issue by mrunelov** [mvk-team42/Veracitor#51]
The database is currently unable to store dots (".") in names. This is especially a problem for URL's. There are private convert methods in place as a workaround, but data is being accessed in unconventional ways in e.g. web/utils.py and web/ratings.py, which means that they also have to implement this conversion.

TODO: Remove any need for external conversion OR fix the storage issue directly.

**Comment by Alfred26** [comment]
The database can store dots in names in general, it is only the keys of source_ratings, info_ratings and group_ratings that are affected. As the URL is the unique identifier of information entities, it is also the key mapping informations to ratings.

**Comment by Alfred26** [comment]
Should be fixed now (apart from group, but that's not as critical). Use everything as normal, the database modules should handle all necessary conversions.
