### ISSUE TITLE
Minnesläcka i webläsaren!

### ISSUE THREAD

**Issue by johnbrynte** [mvk-team42/Veracitor#52]
Det finns en fet minneslucka i webapplikationen; **Hjälp till att debugga!** :(

As Kanye West said:

> We're living the future so
> the present is our past.

**Comment by mold** [comment]
Har forskat lite! Ni kan testa samma saker själva (t.ex. med system monitor vid sidan, se bild).
- Både minnesanvändningen och CPU-belastningen ökar/läcker.
- Minnesluckan uppstår i nätverksvyn när man utökar nätverket genom att klicka på en nod.
- Det är uppenbarligen fel i javascript eftersom luckorna uppstår på klienten.

Detta händer när man försöker expandera nätverket:
![hey mr graph](https://f.cloud.github.com/assets/1492711/487310/bf9ad688-b953-11e2-847b-882d8880294c.jpg)

John, tror du har lättast att lösa detta.

**Comment by johnbrynte** [comment]
Tillfälligt löst, lagd på is.
