### ISSUE TITLE
Database consistency

### ISSUE THREAD

**Issue by mold** [mvk-team42/Veracitor#53]
Vi fick nyss ett problem när informationsobjekt togs bort ur databasen. Producers som "ägde" dessa har sedan kvar null-referenser, och allt blir dåligt.

Så när man tar bort informationsobjekt borde de tas bort från producers, och vice versa.

**Comment by Alfred26** [comment]
Det är fixat för tillfället. Triggers finns nu också tillagda för information references, samt så försvinner en users grupper då en user deletas. Problem återstår dock med source_ratings och info_ratings. Om en exempelvis en producer tas bort så tas inte ratings på den producern bort.

**Comment by mrunelov** [comment]
Det är ett problem. T.ex. i Ratings-tabben kommer det att krascha klienten ifall man tar bort ratade producernter eller infos då. Men när vi väl har uppe demo-servern så är det ju inget problem, men kanske en wontfix-issue?

**Comment by mold** [comment]
Bra jobbat! Kommer ni fixa för rarings också eller är det för invecklat?

Den fredagen den 10:e maj 2013 skrev Alfred26:

**Comment by Alfred26** [comment]
Jag och Fredrik ska försöka lösa det här med ratings också. Det är mer komplicerat då de inte innehåller själva objekten, men nånting borde vi kunna hitta på.

**Comment by Alfred26** [comment]
Ratings borde nu också uppdateras vid varje extrahering och save av producer/user.
