### ISSUE TITLE
sortering av tags

### ISSUE THREAD

**Issue by JonathanMurray** [mvk-team42/Veracitor#54]
Kan vara bra att ha tags sorterade efter hur ofta de förekommer, i dropdownlistsen där man ser dem. Man vill ju fokusera på de tags som faktiskt används ofta.

Skulle kunna lösa det med ett fält i Tag-objekt i db, som inkrementeras när taggen används. Då kan man enkelt sortera på det attributet.

**Comment by mold** [comment]
Denna förtjänar en "wontfix". Finns ingen nytta med det här förutom att
göra hemsidan "roligare och tuffare att använda".

/MR sur "jobba ingen lek" Molin

2013/5/10 JonathanMurray notifications@github.com

**Comment by mold** [comment]
Håller förövrigt på med en autocomplete-selector för tags, och undrar mer
över när och om vi ska satsa på att göra en tagg-hierarki med tillhörande
selector?

2013/5/10 Daniel T Molin dkd333@gmail.com

**Comment by mrunelov** [comment]
Tag-hierarki är tanken vi ska bygga efter, utan att implementera. Glöm inte att tags inte ska vara ett hav av beskrivande taggar som på typ twitter. Eftersom vi alltid bara ratar inom en enda tag är det snarare kvalitet framför kvantitet. Jag röstar för wontfix just nu, men om någon får tid över får dom gärna kika på det. Popularitet vore ju nice att ha.

**Comment by mold** [comment]
:100: :+1:
