### ISSUE TITLE
Maxlängd på taggar

### ISSUE THREAD

**Issue by mrunelov** [mvk-team42/Veracitor#55]
Inte säker på hur man ska implementera det, men vi behöver en maxlängd på taggar.

Antingen så fixar man det själv innan man sparar taggen så man kan kapa det man vill kapa, eller så kapar databasen automatiskt efter en viss gräns.

Hursomhelst, kanske max 20-30 tecken.

**Comment by johnbrynte** [comment]
Jag anser det som en självklarhet att applikationen helt bör styras av fördefinierade taggar, speciellt om vi ska ha tagg-hierarkier.

**Comment by glindstedt** [comment]
tycker också att fördefinierade verkar vettigt, frågan blir hur vi ska hantera crawlad information, då taggarna som fås från dom troligtvis inte kommer stämma med de vi definierat... ska vi skippa automatisk taggning helt då eller regexa lite på det vi hittar?

**Comment by mrunelov** [comment]
Jag säger skippa. Bortom vårt scope.

**Comment by JonathanMurray** [comment]
Jag ser det såhär:

Det scrapas fram artiklar som ibland har ett fåtal (rätt usla) tags. Förhoppningsvis har folk dock lite vett och använder någorlunda vanliga ord och ung. samma som andra artiklar.

Totalt kommer det att finnas säkert mer än 200 halvkassa tags, men det löser vi genom att ha ca 10 st fördefinierade tags som vi låter vara supertags till skit-tagsen. Man kan ju göra som så att användarna i GUI:t bara får se de fördefinierade, och inte behöver veta om scrapade tags. Detta gör ju att vi inte gång på gång måste tagga upp artiklar, utan endast definiera tag-hierarkin; efter att tilräckligt många skit-tags har stoppats in under nån supertag kan resten skötas av scrapningen! :dancers:

**Comment by JonathanMurray** [comment]
- News
  - Crime
  - Culture
  - Politics
  - Sports
  - Finances

**Comment by mrunelov** [comment]
Sammanfattning: 
Gör det ni känner att ni har tid för, men prototypen är inte tänkt att ha kvalitativa tags, så det är ingen press på att få med något. Vi vill definitivt inte ha många tags, så förslaget ovan ser bra ut.

**Comment by mold** [comment]
Vi kom alltså förut fram till att det (ungefär) ska fungera så här:

Systemet innehåller ett antal fördefinierade taggar, cirka 10 stycken tillräckligt beskrivande (news, sports, politics, science etc.). Crawlern hittar informations med de ökända skittaggarn som översätts av crawlern till en av taggarna som finns i systemet

Låter det bra?
