### ISSUE TITLE
Svengelska in Issues.

### ISSUE THREAD

**Issue by mrunelov** [mvk-team42/Veracitor#57]
Det är mycket blandning mellan svenska och engelska i issues! Oklart om en issue ska ses som dokumentation eller chat och därför förvirras vi. Själv kör jag 50/50 ungefär.

 :dancers:

**Comment by mold** [comment]
Well I don't see a problem with att blanda språk sometimes

2013/5/12 mrunelov notifications@github.com

**Comment by mrunelov** [comment]
Clearly resolved
