### ISSUE TITLE
om man kör scrape article på nåt som inte är en artikel så kommer den ändå fösöka lägga till

### ISSUE THREAD

**Issue by glindstedt** [mvk-team42/Veracitor#58]
ska vi försöka lägga till? isf kan man använda den för att manuellt lägga till information som vår automatiska scrape av någon anledning rejectar...

annars borde man lägga till en "is_article" koll i articleSpider

**Comment by JonathanMurray** [comment]
Lade till en is_article-koll i articleSpider.
