### ISSUE TITLE
Request fail vid expandering i nätverket

### ISSUE THREAD

**Issue by johnbrynte** [mvk-team42/Veracitor#68]
Ibland failar requests till _/jobs/network/neighbors_ i fetch_neighbors() i visualizer.js. Loggen på servern visar att requesten avslutas med statuskod **200** medan klienten istället får tillbaka statuskod **0**.

Problemet verkar uppstå när noder med många ratings expanderas, men så vitt jag förstår ska inte en request ha någon direkt tidsbegränsning? En lösning skulle i sådana fall vara att göra om _/jobs/network/neighbors_ till en task, något som dessvärre skulle sega ner graftraverseringen.

**Comment by mrunelov** [comment]
statuskod 0? Är det att response var helt tom?

**Comment by johnbrynte** [comment]
Snarare att ingen _response_ kom tillbaka från servern, som att förbindelsen bara bröts.

**Comment by johnbrynte** [comment]
Problemet verkar bara uppstå när jag använder tunnling i putty på min Windows-burk, så problemet torde vara löst. Även om problemet skulle dyka upp krashar inte applikationen, utan användaren tvingas bara klicka en extra gång på noden.
